name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install dependencies
        run: yarn install

      - name: ESLint Check
        run: yarn lint

      - name: Unit Testing
        run: yarn test

      - name: Build project
        run: yarn build
        env:
          VUE_APP_ASSET_API_URL: ${{ secrets.APP_ASSET_API_URL }}
          VUE_APP_ASSIGNMENT_API_URL: ${{ secrets.APP_ASSIGNMENT_API_URL }}
          VUE_APP_USER_API_URL: ${{ secrets.APP_USER_API_URL }}
          VUE_APP_SETTINGS_API: ${{ secrets.APP_SETTINGS_API }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
