name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install dependencies
        run: yarn install

      - name: ESLint Check
        run: yarn lint

  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Install dependencies
        run: yarn install

      - name: Unit Testing
        run: yarn test:unit

  merge-checks:
    name: Merge Checks
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    steps:
      - id: automerge
        name: Merge pull requests (automerge-action)
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
