name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: ESLint Check
        run: yarn lint

  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Unit Testing
        run: yarn test:unit

  merge-checks:
    name: Merge Checks
    runs-on: ubuntu-latest
    needs: [lint, unit-test]

    steps:
      - name: Merge Checks
        run: echo "All checks passed. Ready to merge!"

      - name: Merge PR
        if: success() && github.event_name == 'pull_request'
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/merge"
